@echo off
echo Starting Quantum AI Hologram...
cd sphere-main\QuantumAI-Hologram
echo Installing dependencies...
call npm install --legacy-peer-deps
echo Starting hologram server on port 5174...
call npm run dev -- --port 5174
pause