@echo off
echo Starting Quantum AI Avatar (TalkingHead)...
cd TalkingHead-main\TalkingHead-main
echo Installing dependencies...
call npm install
echo Starting avatar server on port 8000...
call npm start
pause